{{- if .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccount.name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.frontend.serviceAccount.annotations | nindent 4 }}
{{- end }}
