apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflare-secrets
  namespace: default
spec:
  provider: gcp
  secretObjects:                                # Add this section to create a Kubernetes secret
  - secretName: cloudflare-secrets
    type: kubernetes.io/tls
    data:
    - objectName: tls.crt
      key: tls.crt
    - objectName: tls.key
      key: tls.key
  parameters:
    secrets: |
      - resourceName: "projects/logical-acolyte-423107-b5/secrets/cloudflare-cert/versions/latest"
        fileName: "tls.crt"
      - resourceName: "projects/logical-acolyte-423107-b5/secrets/cloudflare-key/versions/latest"
        fileName: "tls.key"
