apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflare-secrets
  namespace: default
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/logical-acolyte-423107-b5/secrets/cloudflare-cert/versions/latest"
        fileName: "tls.crt"
      - resourceName: "projects/logical-acolyte-423107-b5/secrets/cloudflare-key/versions/latest"
        fileName: "tls.key"
