echo_server:
  name: echo-server
  replicaCount: 3

  image:
    repository: ghcr.io/yanirw/echo-server
    pullPolicy: IfNotPresent
    tag: "3.0.0"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    name: "echo-server-sa"
    create: true
    annotations:
      iam.gke.io/gcp-service-account: k8s-sa@logical-acolyte-423107-b5.iam.gserviceaccount.com

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 5000

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  ingress:
    enabled: true
    path: "/echo"
    servicePort: 80

frontend:
  name: frontend
  replicaCount: 3

  image:
    repository: ghcr.io/yanirw/frontend
    pullPolicy: IfNotPresent
    tag: "3.0.1"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    name: "frontend-sa"
    create: true
    annotations:
      iam.gke.io/gcp-service-account: k8s-sa@logical-acolyte-423107-b5.iam.gserviceaccount.com

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 3000


  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

  ingress:
    enabled: true
    path: "/"
    servicePort: 80


global:
  ingress:
    host: "yanirw.com"
    className: "gce"
    tls:
      enabled: true
      secretName: "cloudflare-tls"
