echo_server:
  name: echo-server
  replicaCount: 1

  image:
    repository: ghcr.io/yanirw/echo-server
    pullPolicy: IfNotPresent
    tag: "2.1"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 5000

  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

frontend:
  name: frontend
  replicaCount: 1

  image:
    repository: ghcr.io/yanirw/frontend
    pullPolicy: IfNotPresent
    tag: "2.1"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 3000


  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}


ingress:
  enabled: true
  className: ""
  annotations:
    # "kubernetes.io/ingress.class": "nginx"
    # "kubernetes.io/tls-acme": "true"
  hosts:
    - host: "frontend.local"
      paths:
        - path: /(/|$)(.*)
          pathType: Prefix
          serviceName: frontend
          servicePort: 3000
    - host: "echo-server.local"
      paths:
        - path: /echo(/|$)(.*)
          pathType: Prefix
          serviceName: echo_server
          servicePort: 5000
  tls: []  # TLS settings array, populate if necessary
