{{- if .Values.echo_server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "echo_server.fullname" . }}
  labels:
    {{- include "echo_server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.echo_server.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.echo_server.ingress.className }}
  rules:
  - host: {{ .Values.echo_server.ingress.host }}
    http:
      paths:
      - path: /echo
        pathType: Prefix
        backend:
          service:
            name: {{ include "echo_server.fullname" . }}
            port:
              number: {{ .Values.echo_server.ingress.servicePort }}
  {{- if .Values.echo_server.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.echo_server.ingress.host }}
      secretName: {{ .Values.echo_server.ingress.tls.secretName }}
  {{- end }}
{{- end }}
