apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.ingress.tls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - "{{ .Values.ingress.hostname }}"
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
  - host: "{{ .Values.ingress.hostname }}"
    http:
      paths:
      - path: /echo(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "echo_server.fullname" . }}
            port:
              number: {{ .Values.services.echo_server.port }}
      - path: /(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "frontend.fullname" . }}
            port:
              number: {{ .Values.services.frontend.port }}
