{{- if  .Values.echo_server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.echo_server.serviceAccount.annotations | nindent 4 }}
{{- end }}
