name: Build Microservice

on:
  workflow_dispatch:
    inputs:
      build-echo-server:
        description: 'Build Echo Server?'
        required: true
        type: boolean
      build-frontend:
        description: 'Build Frontend?'
        required: true
        type: boolean
      branch:
        description: 'Branch for build'
        required: true
        type: string
  
  workflow_call:
    inputs:
      service-name:
        description: 'The name of the service'
        required: true
        type: string
      service-path:
        description: 'The path to the service'
        required: true
        type: string
      branch:
        description: 'Branch for build'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set service path and name from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ github.event.inputs.build-echo-server }}" == 'true' ]]; then
            echo "SERVICE_NAME=echo-server" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.build-frontend }}" == 'true' ]]; then
            echo "SERVICE_NAME=frontend" >> $GITHUB_ENV
          else
            echo "No service selected for build."
            exit 1
          fi
        shell: bash

      - name: Set service path and name from workflow_call
        if: github.event_name == 'workflow_call'
        run: |
          echo "SERVICE_NAME=${{ inputs.service-name }}" >> $GITHUB_ENV
          echo "SERVICE_PATH=${{ inputs.service-path }}" >> $GITHUB_ENV
        shell: bash

      - name: Log into GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.event.inputs.service-path }}
          file: ${{ github.event.inputs.service-path }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.SERVICE_NAME }}:${{ github.event.inputs.branch }}
