name: Publish New Release

on: 
  workflow_dispatch:
  pull_request:
    paths:
      - 'infra/**'
      - 'app/**'
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
