name: New Github Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Type of version increment to apply (major, minor, patch)'
        required: false
        default: 'patch'
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  issues: write
      
jobs:
  version-bump-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensuring permissions for checkout

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install bumpversion
        run: pip install bumpversion

      - name: Configure Git
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: Bump version and get new tag
        id: bump_version
        run: |
          bumpversion ${{ github.event.inputs.version-type }} --list --allow-dirty
          VERSION=$(cat app/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git add -A
          git diff-index --quiet HEAD || git commit -am "Bump version to $VERSION"
          git tag $VERSION

      - name: Push changes
        run: |
          git push --tags --force
          git push --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: "New release ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
