name: helm_deploy

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'infra/helm/charts/**'
      - 'infra/helm/env/**'
    types:
      - closed

jobs:
  helm_deploy:
    name: Helm Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: 'guitarnetes-gke'
        location: 'us-east1'

    - name: Helm Upgrade for All Charts
      run: |
        for chart in ./infra/helm/charts/*; do
            if [ -d "$chart" ]; then
                echo "Upgrading Helm chart in $(basename $chart)..."
                helm upgrade -i $(basename $chart) $chart -f ./infra/helm/env/values-dev.yaml
            fi
        done

    - name: Verify Installation
      run: |
        kubectl get pods
        kubectl get services
      continue-on-error: true
