name: Helm ci

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/helm/**'  
  pull_request:
    paths:
      - 'infra/helm/**'

jobs:
  helm_template:
    name: Helm Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Lint Helm Charts
      run: |
        for chart in ./infra/helm/charts/*; do
          if [ -d "$chart" ] && [ -e "$chart/Chart.yaml" ]; then
            echo "Linting $(basename $chart)..."
            # Determine the environment-specific values file path based on the chart name
            values_file="./infra/helm/charts/$(basename $chart)/env/values-dev.yaml"
            if [ -e "$values_file" ]; then
              helm lint $chart -f $values_file
            else
              echo "Values file not found for $(basename $chart), using default values"
              helm lint $chart
            fi
            if [ $? -ne 0 ]; then
              echo "Error in Helm lint for $(basename $chart)"
              exit 1
            fi
          else
            echo "Skipping $(basename $chart), not a chart directory or Chart.yaml missing"
          fi
        done
        echo "Linting completed successfully"

    - name: Template Helm Charts
      run: |
        for chart in ./infra/helm/charts/*; do
          if [ -d "$chart" ] && [ -e "$chart/Chart.yaml" ]; then
            chart_name=$(basename $chart)
            echo "Templating $chart_name..."
            # Determine the environment-specific values file path based on the chart name
            values_file="./infra/helm/charts/$chart_name/env/values-dev.yaml"
            if [ -e "$values_file" ]; then
              helm template "$chart_name" $chart -f $values_file
            else
              echo "Values file not found for $chart_name, using default values"
              helm template "$chart_name" $chart
            fi
            if [ $? -ne 0 ]; then
              echo "Error in Helm template for $chart_name"
              exit 1
            fi
          else
            echo "Skipping $(basename $chart), not a chart directory or Chart.yaml missing"
          fi
        done
        echo "Templating completed successfully"
