name: helm ci

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/helm/**'  
  pull_request:
    paths:
      - 'infra/helm/**'

jobs:
  helm_template:
    name: Helm Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Lint Helm Charts
      run: |
        for chart in ./infra/helm/charts/*; do
          if [ -d "$chart" ] && [ -e "$chart/Chart.yaml" ]; then
            echo "Linting $(basename $chart)..."
            helm lint $chart -f ./infra/helm/env/values-dev.yaml
            if [ $? -ne 0 ]; then
              echo "Error in Helm lint for $(basename $chart)"
              exit 1
            fi
          else
            echo "Skipping $(basename $chart), not a chart directory or Chart.yaml missing"
          fi
        done
        echo "Linting completed successfully"

    - name: Template Helm Charts
      run: |
        for chart in ./infra/helm/charts/*; do
          if [ -d "$chart" ] && [ -e "$chart/Chart.yaml" ]; then
            echo "Templating $(basename $chart)..."
            helm template $(basename $chart) $chart -f ./infra/helm/env/values-dev.yaml
            if [ $? -ne 0 ]; then
              echo "Error in Helm template for $(basename $chart)"
              exit 1
            fi
          else
            echo "Skipping $(basename $chart), not a chart directory or Chart.yaml missing"
          fi
        done
        echo "Templating completed successfully"
