name: helm ci

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/helm/**'  
  pull_request:
    paths:
      - 'infra/helm/**'
    
  
jobs:
  helm_template:
    name: Helm Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
       ref: ${{ github.event.pull_request.head.sha }}


    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Lint Helm Chart
      run: |
        helm lint  helm lint ./infra/helm/charts/* -f ./infra/helm/env/values-dev.yaml
        if [ $? -ne 0 ]; then
          echo "Error in Helm lint"
          exit 1
        else
          echo "Lint is successful"  
        fi
      
    - name: Helm Template for All Charts
      run: |
        for chart in ./infra/helm/charts/*; do
          if [ -d "$chart" ]; then
            echo "Processing $(basename $chart)..."
            helm template $(basename $chart) $chart -f ./infra/helm/env/values-dev.yaml
            if [ $? -ne 0 ]; then
              echo "Error in helm template for $(basename $chart)"
              exit 1
            fi
          fi
        done
        echo "All Helm charts processed successfully"
        exit 0