name: Terraform Apply

on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    
jobs:
  apply:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/terraform apply ') && github.event.comment.user.login == 'yanirw' }}
    runs-on: ubuntu-latest
    name: Apply terraform plan

    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2 

      - name: Extract environment from comment
        id: get-env
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          ENVIRONMENT=$(echo $COMMENT_BODY | awk '{print $3}')
          echo "environment=$ENVIRONMENT" >> $GITHUB_ENV
      
      - id: init
        run: terraform init
        working-directory: infra/tf

      - name: Select Workspace
        working-directory: infra/tf
        run: |
          terraform workspace select ${{ env.environment }}
      
  
      - name: terraform apply
        working-directory: infra/tf
        run: terraform apply -var-file=env/${{ env.environment }}.tfvars -auto-approve -no-color
